spring.datasource.url=jdbc:mysql://localhost:3306/db_propiedades_test
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.username=root
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

# Limpieza absoluta de tablas en cada ejecución de test
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=false

# URL ficticia para simular llamadas Feign en ambiente de pruebas
ms.anfitriones.url=http://localhost:9999

# Desactivar Swagger en tests para acelerar el arranque
springdoc.api-docs.enabled=false
springdoc.swagger-ui.enabled=false