# CONFIGURACIÓN BASE (Común para todos)

spring:
  application:
    name: ms-propiedades
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}

server:
  port: ${SERVER_PORT:8081}

---

# PERFIL DE DESARROLLO (dev)

spring:
  config:
    activate:
      on-profile: dev

  # Base de datos MySQL de desarrollo
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/db_propiedades_dev}
    username: ${SPRING_DATASOURCE_USERNAME:root}
    password: ${SPRING_DATASOURCE_PASSWORD:}
    driver-class-name: com.mysql.cj.jdbc.Driver

  # Estrategia de Hibernate para desarrollo
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true

# Documentación interactiva con Swagger UI
springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    path: /doc/swagger-ui.html


# ENLACE CON LA TORRE DE CONTROL EUREKA
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://localhost:8761/eureka/}
  instance:
    prefer-ip-address: true

---

# PERFIL DE PRUEBAS (test)

spring:
  config:
    activate:
      on-profile: test

  # Base de datos MySQL de pruebas
  datasource:
    url: jdbc:mysql://localhost:3306/db_propiedades_test
    username: root
    password: ""
    driver-class-name: com.mysql.cj.jdbc.Driver

  # Limpieza absoluta de tablas en cada ejecución de test
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    show-sql: false
    hibernate:
      ddl-auto: create-drop

# Desactivar Swagger en tests para acelerar el arranque
springdoc:
  api-docs:
    enabled: false
  swagger-ui:
    enabled: false

# URL ficticia para simular llamadas Feign en ambiente de pruebas
ms:
  anfitriones:
    url: http://localhost:9999

---

# PERFIL DE PRODUCCIÓN (prod)
spring:
  config:
    activate:
      on-profile: prod
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: validate

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE}

ms:
  anfitriones:
    url: ${MS_ANFITRIONES_URL}








